name: Unit tests

on:
  push:
    branches:
      - master
      - i1074-gh-actions
  pull_request:
    branches:
      - '**'

jobs:

  build-and-test:
    name: Unit tests on a number of OS and Python versions
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-16.04, ubuntu-latest, macos-latest, windows-latest]
        python-version: [2.7, 3.5, 3.6, 3.7, 3.8]

    steps:
      - uses: actions/checkout@v1

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - name: install python bindings
        run: |
          python --version
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install .

      - name: python unit tests
        run: |
          python run-tests.py --unit
